# use containers
sudo: true

os:
  - linux
  - osx

language: cpp

cache: ccache

matrix:
  include:
  - os: osx
    compiler: clang
  - os: osx
    compiler: gcc
  - os: linux
    compiler: gcc

addons:
  apt:
    sources:
      - george-edison55-precise-backports
    packages:
      - cmake
      - cmake-data

before_install:
  - if [ "$TRAVIS_OS_NAME" == "osx" ];  then echo "need cmake 3.2"; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew update && brew install ccache; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then export PATH="/usr/local/opt/ccache/libexec:$PATH"; fi
  - git clone --branch=v0.3.5 https://github.com/google/glog
  - cd glog
  - cmake -DCMAKE_INSTALL_PREFIX=/Users/travis/GLOG-INSTALL
  - make
  - sudo make install
  - cd ..
  - git clone --branch v2.2.0 https://github.com/ANTsX/ANTs.git ~/ANTs
  - pwd
  - ls
  - mkdir ~/antsbin
  - cd ~/antsbin

script:
  - cmake -DCMAKE_BUILD_TYPE=Release -DRUN_LONG_TESTS=OFF -DRUN_SHORT_TESTS=ON ~/ANTs && make -j2 --keep-going && cd ANTS-build/ && make test
  - cd /Users/travis/build/UCL/petmr-RESOLUTE && cmake -DCMAKE_BUILD_TYPE=Release -DITK_DIR=/Users/travis/antsbin/ITKv4-build -DANTs_SOURCE_DIR=~/ANTs -DANTs_LIBRARY_DIR=/Users/travis/antsbin/lib -Dglog_DIR=/Users/travis/GLOG-INSTALL/lib/cmake/glog && make -j2
