language: generic

sudo: true

matrix:
  include:
  - os: osx
    compiler: gcc
    env:
        - MATRIX_EVAL="brew install gcc5 && CC=gcc-5 && CXX=g++-5"
  - os: linux
    compiler: gcc
    env: COMPILER_NAME=gcc CXX=g++-5 CC=gcc-5

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - cmake
      - cmake-data
      - g++-5
      - libboost-all-dev
      - libgtest-dev
      - libdcmtk2-dev
      - libgflags-dev
      - libgoogle-glog-dev
      - wget

before_install:
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then echo "need cmake 3.2"; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew update && brew install glog ; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew upgrade cmake; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install dcmtk; fi

before_script:
  - git clone https://github.com/google/glog ~/glog
  - if [ ! -e ~/glog-build/install_manifest.txt ]; then
        mkdir -p ~/glog-build &&
        cd ~/glog-build &&
        cmake -DCMAKE_BUILD_TYPE=Release ~/glog &&
        make -j2;
      fi
  - cd ~/glog-build
  - sudo make install #step 1 to here
  - git clone --branch=release-1.8.0 https://github.com/google/googletest ~/googletest
  - if [ ! -e ~/googletest-build/install_manifest.txt ]; then
        mkdir -p ~/googletest-build &&
        cd ~/googletest-build &&
        cmake -DCMAKE_BUILD_TYPE=Release ~/googletest &&
        make -j2;
    fi
  - cd ~/googletest-build
  - sudo make install #step 1 to here
  - git clone --branch=v3.1.1 https://github.com/nlohmann/json.git ~/json
  - cd ~/json
  - cmake -DBUILD_TESTING=OFF .
  - make -j2
  - sudo make install
  - cd ~
  - git clone --branch=v2.2.0 https://github.com/ANTsX/ANTs.git ~/ANTs
  - if [ ! -e ~/ANTS-BUILD/ANTS-build ]; then
        mkdir -p ~/ANTS-BUILD &&
        cd ~/ANTS-BUILD &&
        cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTING:BOOL=OFF ~/ANTs && make -j2;
    fi #step 4 to here

script:
  - ls ~/ANTS-BUILD
  - cd ~/build/UCL/petmr-RESOLUTE && cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTING=ON -DITK_DIR=$HOME/ANTS-BUILD/ITKv4-build -DANTs_SOURCE_DIR=$HOME/ANTs -DANTs_LIBRARY_DIR=$HOME/ANTS-BUILD/lib && make -j2 && ctest --verbose
