language: generic

sudo: true

cache:
- directories:
  - $HOME/googletest
  - $HOME/googletest-build
  - $HOME/ITK-BUILD
  - $HOME/ITK-INSTALL
  - $HOME/ANTS-BUILD

addons:
  apt:
    sources:
      - george-edison55-precise-backports
      - llvm-toolchain-precise-3.8
      - ubuntu-toolchain-r-test
    packages:
      - cmake
      - cmake-data
      - g++-5
      - libboost-all-dev
      - libgtest-dev
      - libdcmtk2-dev
      - ccache
      - libgflags-dev
      - libgoogle-glog-dev
      - wget

matrix:
  include:
  - os: osx
    compiler: clang
  - os: osx
    compiler: gcc
  - os: linux
    compiler: gcc
    env: COMPILER_NAME=gcc CXX=g++-5 CC=gcc-5

before_script:
  - if [ "$TRAVIS_OS_NAME" == "osx" ];  then echo "need cmake 3.2"; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew update && brew install ccache glog ; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install dcmtk; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then export PATH="/usr/local/opt/ccache/libexec:$PATH"; fi
  - ls ~
  - if [ ! -e ~/googletest-build/install_manifest.txt ]; then
        git clone https://github.com/google/googletest ~/googletest &&
        mkdir -p ~/googletest-build &&
        cd ~/googletest-build &&
        cmake -DCMAKE_BUILD_TYPE=Release ~/googletest &&
        make -j4;
    fi
  - cd ~/googletest-build
  - sudo make install #step 1 to here
  - git clone --branch=v3.1.1 https://github.com/nlohmann/json.git ~/json
  - cd ~/json/include
  - sudo ln -s nlohmann /usr/local/include #step 2 to here
  - cd ~
  - git clone --branch=v4.12.0 https://github.com/InsightSoftwareConsortium/ITK.git ~/ITK
  - if [ ! -e ~/ITK-BUILD/ITKConfig.cmake ]; then
        cd ~/ITK &&
        mkdir -p ~/ITK-BUILD && mkdir -p ~/ITK-INSTALL &&
        cd ~/ITK-BUILD &&
        cmake -DCMAKE_INSTALL_PREFIX=~/ITK-INSTALL -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTING:BOOL=OFF -DBUILD_EXAMPLES:BOOL=OFF -DITK_LEGACY_REMOVE:BOOL=ON -DITK_FUTURE_LEGACY_REMOVE:BOOL=ON -DITKV3_COMPATIBILITY:BOOL=OFF -DITK_BUILD_DEFAULT_MODULES:BOOL=ON -DKWSYS_USE_MD5:BOOL=ON -DITK_WRAPPING:BOOL=OFF -DModule_MGHIO:BOOL=ON -DModule_ITKReview:BOOL=ON ~/ITK &&
        make -j4 --keep-going && make install;
    fi #step 3 to here
  - ls ~/ITK-INSTALL
  - cd ~/ITK-BUILD
  - git clone --branch=v2.2.0 https://github.com/ANTsX/ANTs.git ~/ANTs
  - if [ ! -e ~/ANTS-BUILD/ANTs-build ]; then
        mkdir -p ~/ANTS-BUILD &&
        cd ~/ANTS-BUILD &&
        cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTING:BOOL=OFF -DUSE_SYSTEM_ITK=ON -DITK_DIR=$HOME/ITK-INSTALL ~/ANTs && make -j2 --keep-going;
    fi #step 4 to here

script:
  - ls ~/ANTS-BUILD
  - cd ~/build/UCL/petmr-RESOLUTE && cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTING=ON -DITK_DIR=$HOME/ANTS-BUILD/ITKv4-build -DANTs_SOURCE_DIR=$HOME/ANTs -DANTs_LIBRARY_DIR=$HOME/ANTS-BUILD/lib && make -j4 && ctest --verbose
