language: generic

sudo: true

cache:
- directories:
  - $HOME/antsbin
  - $HOME/googletest
  - $HOME/googletest-build
  - $HOME/json
  - $HOME/ANTs
  - $HOME/ITK
  - $HOME/ITK-BUILD

addons:
  apt:
    sources:
      - george-edison55-precise-backports
      - llvm-toolchain-precise-3.8
      - ubuntu-toolchain-r-test
    packages:
      - cmake
      - cmake-data
      - g++-5
      - libboost-all-dev
      - libgtest-dev
      - libdcmtk2-dev
      - ccache
      - libgflags-dev
      - libgoogle-glog-dev
      - wget

matrix:
  include:
  - os: osx
    compiler: clang
  - os: osx
    compiler: gcc
  - os: linux
    compiler: gcc
    env: COMPILER_NAME=gcc CXX=g++-5 CC=gcc-5

before_script:
  - if [ "$TRAVIS_OS_NAME" == "osx" ];  then echo "need cmake 3.2"; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew update && brew install ccache glog ; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install dcmtk; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then export PATH="/usr/local/opt/ccache/libexec:$PATH"; fi
  - if [ ! -d ~/googletest ]; then git clone https://github.com/google/googletest; fi
  - if [ ! -d ~/googletest-build/bin ]; then
        mkdir ~/googletest-build &&
        cd ~/googletest-build &&
        cmake -DCMAKE_BUILD_TYPE=Release ~/googletest &&
        make -j4;
    fi
  #- cd ~/googletest-build
  #- sudo make install
  #- if [ ! -e ~/json ]; then git clone --branch=v3.1.1 https://github.com/nlohmann/json.git ~/json; fi
  #- cd ~/json/include
  #- sudo ln -s nlohmann /usr/local/include
  #- cd ~
  #- if [ ! -e ~/ANTs ]; then git clone --branch=v2.2.0 https://github.com/ANTsX/ANTs.git ; fi
  #- if [ ! -e ~/ITK ]; then git clone --branch=v4.13.0 https://github.com/InsightSoftwareConsortium/ITK.git; fi
  #- if [ ! -e ~/ITK-BUILD ]; then
#        mkdir ~/ITK-BUILD &&
#        cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_EXAMPLES=OFF -DBUILD_TESTING=OFF -DModule_ITKReview=ON ~/ITK &&
#        make -j2 --keep-going
#    fi

script:
  - pwd
  - ls
  - ls /usr/local/include

#  - |
#    if [ ! -e ~/antsbin/ANTs-build ]; then
#        if [ ! -e ~/antsbin ]; then mkdir ~/antsbin; fi
#        cd ~/antsbin;
#        cmake -DCMAKE_BUILD_TYPE=Release -DRUN_LONG_TESTS=OFF -DRUN_SHORT_TESTS=OFF -DUSE_SYSTEM_ITK=ON ~/ANTs && make -j4 --keep-going
#    fi
#  - cd ~/build/UCL/petmr-RESOLUTE && cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTING=ON -DITK_DIR=~/antsbin/ITKv4-build -DANTs_SOURCE_DIR=~/ANTs -DANTs_LIBRARY_DIR=~/antsbin/lib && make -j4 && ctest --verbose
