language: cpp
dist: trusty

sudo: true

cache: ccache

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - cmake
      - cmake-data
      - build-essential
      - g++-5
      - ccache
      - libboost-all-dev

matrix:
  include:
  - os: osx
    compiler: clang
  - os: osx
    compiler: gcc
  - os: linux
    compiler: gcc
    env: COMPILER_NAME=gcc CXX=g++-5 CC=gcc-5

before_install:
  - if [ "$TRAVIS_OS_NAME" == "osx" ];  then echo "need cmake 3.2"; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew update && brew install ccache; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then export PATH="/usr/local/opt/ccache/libexec:$PATH"; fi
  - |
    if [ ! -e ~/glog ]; then
        cd ~
        git clone --branch=v0.3.5 https://github.com/google/glog
        cd glog
        cmake  -DCMAKE_BUILD_TYPE=Release . -DCMAKE_INSTALL_PREFIX=./INSTALL
        make -j2
        make install
    fi
  - |
    if [ ! -e ~/json ]; then
        cd ~
        git clone --branch=v3.1.1 https://github.com/nlohmann/json.git
        cd json
        cmake  -DCMAKE_BUILD_TYPE=Release . -DCMAKE_INSTALL_PREFIX=./INSTALL
        make -j2
        make install
    fi
  - cd ~
  - if [ ! -e ~/ANTs ]; then git clone --branch=v2.2.0 https://github.com/ANTsX/ANTs.git ~/ANTs; fi
  - |
    if [ ! -e ~/antsbin ]; then
        mkdir ~/antsbin;
    fi

script:
  - cd ~/antsbin
  - cmake -DCMAKE_BUILD_TYPE=Release -DRUN_LONG_TESTS=OFF -DRUN_SHORT_TESTS=ON ~/ANTs && make -j2 --keep-going && cd ANTS-build/ && make test;
  - cd ~/build/UCL/petmr-RESOLUTE
  - cmake -DCMAKE_BUILD_TYPE=Release -DITK_DIR=~/antsbin/ITKv4-build -DANTs_SOURCE_DIR=~/ANTs -DANTs_LIBRARY_DIR=~/antsbin/lib -Dglog_DIR=~/glog/INSTALL -Dnlohmann_json_DIR=~/json/INSTALL . && make -j2
